### ISSUE TITLE
Add Cocoapods integration

### ISSUE THREAD

**Issue by zhuravel-sergey** [iCepa/Tor.framework#38]
Guys, please add Cocoapods integration 🙏
I have a project on Cocoapods and I cannot integrate your framework :(

Thx!

**Comment by mtigas** [comment]
Ah. @tladesignz: I think when Tor.framework was first being put together it wasn't possible? (Tor has to be built as a static framework and can't be a dynamic library due to the way we compile the already-existing `tor` binary in, and CocoaPods support for that was iffy, I think. But looks fixed now?)

https://github.com/CocoaPods/CocoaPods/issues/6651

https://github.com/CocoaPods/CocoaPods/issues/6772

https://github.com/CocoaPods/CocoaPods/pull/6811

Maybe. This is just a guess since I'm having trouble remembering.

**Comment by zhuravel-sergey** [comment]
How can I manually add a framework to a project without using a Carthage? Thx 😉

**Comment by zhuravel-sergey** [comment]
@tladesignz I already tried and always get the following error:
ld: framework not found Tor
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tladesignz** [comment]
Ah. You also need to drag-and-drop the `Tor.framework` file found in the `Products` folder of the `Tor.framework` project into your app's `Linked Frameworks and Libraries` section in the `General` tab of all targets you want to use it in. (The huge configuration form you get, when you click on the project root in the project navigator.)

**Comment by zhuravel-sergey** [comment]
@tladesignz do you have an example of such a project on Swift? since I get various file linking errors

Thx! 🙏

**Comment by tladesignz** [comment]
Unfortunately not. I use that technique when I develop on OnionBrowser and Tor.framework simultaniously... You can run Carthage and CocoaPods alongside, though. It's annoying, but you'll get over it... ;-)
