### ISSUE TITLE
Upgrade libevent to 2.1.10

### ISSUE THREAD

**Issue by mtigas** [iCepa/Tor.framework#49]
Related to #45.

* https://libevent.org
* https://raw.githubusercontent.com/libevent/libevent/release-2.1.10-stable/ChangeLog

Our libevent is 2.1.8 which was released in January 2017.

2.1.9-beta and 2.1.10 weren't released until earlier this year. It _shouldn't_ have any API/ABI breaking changes, but who knows.

(This is VERY low priority compared to #45.)

**Comment by tladesignz** [comment]
I tried upgrading, compile didn't work afterwards with strange error messages:

```
checking for gcc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64
checking whether the C compiler works... no
configure: error: in `/Users/berhart/workspace/gp/Tor.framework/Tor/libevent':
configure: error: C compiler cannot create executables
See `config.log' for more details
make: *** [config.status] Error 77
```

My knowledge and experience with C compilation is rather limited... Any help is welcome.

Here's the [config.log](https://github.com/iCepa/Tor.framework/files/3309205/config.log).

Since I managed to compile latest Tor and OpenSSL, I released a new version of Tor.framework yesterday.

**Comment by kutsin** [comment]
@mtigas @tladesignz Hi guys. Ive managed to build tor with latest libs, even Libevent 2.1.10 and openssl 1.1.1c. You can see build scripts here: https://github.com/kutsin/tor-ios-build-scripts
Hope it will help you.

It was successfully tested in simulator and iPhone 10. But iPad 3 on iOS 9.3.5 is not working, can't find problem at this moment, but I still trying. May be together we can find a solution :)

**Comment by tladesignz** [comment]
Could upgrade without issues to libevent 2.1.11 with 17a878741d5216a7f2d77103bc97a8aa4916056d! :-)
