### ISSUE TITLE
How to specify custom torrc location?

### ISSUE THREAD

**Issue by Fonta1n3** [iCepa/Tor.framework#89]
I'd like to specify a custom torrc location. Not sure how to accomplish this via the framework, I know you can run a cli arg `-f <path to torrc>` when running tor, is there anyway to accomplish this via the framework?

EDIT: fwiw I just saw you can now add a hidden service via the config options (`config.hiddenServiceDirectory = <URL>`) directly which solves my issue.

**Comment by tladesignz** [comment]
Since Tor is not started as an executable binary but in a thread, I don't think you can actually set a torrc file. I never tried, though.

However, you can set *all* flags, you can find [in the documentation](https://2019.www.torproject.org/docs/tor-manual.html.en) via Tor.framework using the [`TORConfiguration`](https://github.com/iCepa/Tor.framework/blob/pure_pod/Tor/Classes/Core/TORConfiguration.m) class.

Either, there's an explicit option for it available, or you can use the `#options` dictionary or the `#arguments` array.

See the [`#compile`](https://github.com/iCepa/Tor.framework/blob/pure_pod/Tor/Classes/Core/TORConfiguration.m#L51-L138) method to understand how you can achieve what you need.
